export const ACTION_STARTED = "ACTION_STARTED";
export const ACTION_ERROR = "ACTION_ERROR";
export const ACTION_SUCCESS = "ACTION_SUCCESS";

export const GET_UPCOMINGCLASS = "GET_UPCOMINGCLASS";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const GET_CLASSES = "GET_CLASSES";
export const CREATE_CLASS = "CREATE_CLASS";
