export const ACTION_STARTED = "ACTION_STARTED";
export const ACTION_ERROR = "ACTION_ERROR";
export const ACTION_SUCCESS = "ACTION_SUCCESS";

export const SEND_PAGEDATA = "SEND_PAGEDATA";

export const GET_UPCOMINGCLASS = "GET_UPCOMINGCLASS";
export const GET_BOOKING_BY_CLASSID = "GET_BOOKING_BY_CLASSID";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const GET_CLASSES = "GET_CLASSES";
export const CREATE_CLASS = "CREATE_CLASS";
export const SET_CURRENTCLASS = "SET_CURRENTCLASS";
export const GET_COURSES = "GET_COURSES";
